name: tintin
adopt-info: tintin
summary: TinTin++ is a scriptable MUD client.
description: TinTin++ is a MUD client that features an easy to learn yet powerful scripting language, a versatile automapper, and advanced VT100 interface controls.
icon: tintin-128.png

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: i386
  - build-on: amd64

apps:
  tintin:
    command: tt++

parts:
  tintin:
    plugin: autotools
    source: https://github.com/scandum/tintin
    source-type: git
    source-branch: master
    build-packages:
      - gcc
      - make
      - libpcre3-dev
      - zlib1g-dev
      - gnutls-dev
    override-build: |
      src/configure
      mv Makefile config.h src/
      make -j -C src
      cp src/tt++ $SNAPCRAFT_PART_INSTALL/
      snapcraftctl set-version $(head -n 1 mods/igr.mods | awk -F ' ' '{print $3}' | tr -d '\r')
